### ISSUE TITLE
看不了demo页面

### ISSUE THREAD

**Issue by bodyno** [zhongzhi107/grunt-velocity-requirejs-demo#4]
跑起来是一个只有去哪儿title页面

**Comment by lmf** [comment]
你进/demo页了吗，在首页加了个进demo页的连接，你更新下

**Comment by bodyno** [comment]
方便加下qq吗？
还有很多问题想请教你

**Comment by bodyno** [comment]
我qq:411298027

**Comment by lmf** [comment]
已经加了

**Comment by lmf** [comment]
修改了velocity插件问题已经解决。

**Comment by bodyno** [comment]
改成了插件的这个版本是吧？

"velocity": "lmf/velocity"

**Comment by lmf** [comment]
@az8321550 这样就不需要再去修改velocity了
