### ISSUE TITLE
grunt:build 后 css中写有background图片的路径没有加上md5

### ISSUE THREAD

**Issue by bodyno** [zhongzhi107/grunt-velocity-requirejs-demo#6]
grunt:build 后 css中写有background图片的路径没有加上md5

**Comment by bodyno** [comment]
发现如果写的是相对路径就加不上md5

**Comment by zhongzhi107** [comment]
贴一下你的css代码以及目录结构@az8321550

**Comment by bodyno** [comment]
```
`
```

/_background: url("/static/images/demo/macro.png");_/
  background: url("../../../images/demo/macro.png");
`

**Comment by bodyno** [comment]
```
/*background: url("/static/images/demo/macro.png");*/
  background: url("../../../images/demo/macro.png");
```

**Comment by bodyno** [comment]
上面那样就可以
下面那样写就不行

**Comment by zhongzhi107** [comment]
css文件和图片文件的目录关系也贴一下

**Comment by bodyno** [comment]
![u p984 qu8djnw t 3wp6 u](https://cloud.githubusercontent.com/assets/5443058/8073846/20f479c8-0f5d-11e5-9dc7-364e87e79d53.png)

**Comment by bodyno** [comment]
就是这样一个目录

**Comment by zhongzhi107** [comment]
使用相对路径的话，查找时会根据当前css的位置来查找，比如上面的代码在a/b.css中，那么查找图片的地址就是a/../../../images/demo/macro.png，只有存在真实的macro.png物理文件时，替换才能成功

**Comment by bodyno** [comment]
意思是不支持用相对路径？

**Comment by zhongzhi107** [comment]
相对路径也是支持的，但在grunt的各种task（less->css or autoprefixer or concat）处理过程中，难免会改变css和图片的相对位置关系，要维护这个相对位置不容易（如果你愿意折腾，其实也是可以维护的），从经验上来看，推荐使用绝对路径（这样只需要保证图片输出路径不变即可），容易控制

**Comment by bodyno** [comment]
哦，原来是这样
但这有个问题，
随着项目的增大，
路径名也会越来越长，到最后，那是很难维护的
