### ISSUE TITLE
几个问题想请教一下，谢谢

### ISSUE THREAD

**Issue by lileichinasoft** [zhongzhi107/grunt-velocity-requirejs-demo#8]
grunt-velocity-requirejs-demo

问题如下：
1.URL关系映射机制是通过什么插件完成的？
2.node.js版的velocity引擎如何支持toolbox的？
3.对于Velocity语法是全量支持的么？
4.如何指定不同vm引用不同的layout模板？

谢谢回答！

**Comment by lmf** [comment]
1. grunt-connect-route
2. 如何支持的见https://github.com/fool2fish/velocity/
3. 是全量了，具体的见https://github.com/fool2fish/velocity/
4. 全局的layout模版是在config/grunt/velocity.js的macro属性中定义的
